### ISSUE TITLE
[Bug]: playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by abhradeepde123** [elebumm/RedditVideoMakerBot#2033]
### Describe the bug

I don't know what the bug is, but when I do `python main.py` it gives me this.

### Reproduction Steps

I just ran `python main.py` after setting up.

### Expected behavior

I expected it to make a video.

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/141354213/06460fc6-0a38-4fc6-bc49-75f06be2376f)
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/141354213/ed65b5cc-ccad-4fe2-920c-00e54fdce41d)
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/141354213/2262a2d8-d62d-414e-b2bc-1bad699fc8ab)
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/141354213/8dac9d27-da20-4cc9-9589-0e090f83fd15)

### System Information

Operating System : Windows 11
Python version : Python 3.10
App version / Branch : latest (3.2.1)
IDE: PyCharm 2023.3.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Here's the full log (copy-pasted):

```
Using region England server backend.


██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝



   Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free to join my Discord server or submit a GitHub issue.
                              You can find solutions to many common problems in the documentation: https://reddit-video-maker-bot.netlify.app/


┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using the newest version (3.2.1) of the bot                                                                                                                       │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
###############################
|                             |
| Checking TOML configuration |
|                             |
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                                                                                 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
Version 7.7.0 of praw is outdated. Version 7.7.1 was released Tuesday July 11, 2023.
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                                                                              │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from TOML config
NSFW Post Detected. Skipping...
NSFW Post Detected. Skipping...
Video will be: Parents of identical twins, how did you avoid getting them confused as babies? �
Thread url is: https://reddit.com/r/AskReddit/comments/1cf4a9u/parents_of_identical_twins_how_did_you_avoid/ �
Thread has 411 upvotes
Thread has a upvote ratio of 93.0%
Thread has 184 comments
Received subreddit threads Successfully.
Thread ID is 1cf4a9u
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 3.1 it/s  
Saved Text to MP3 files successfully.
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                                                                                │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Logging in to Reddit...
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                          │
│ Version: 3.2.1                                                                                                                                                            │
│ Error: Timeout 30000ms exceeded.                                                                                                                                          │
│ =========================== logs ===========================                                                                                                              │
│ waiting for locator("[name=\"username\"]")                                                                                                                                │
│ ============================================================                                                                                                              │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': │
│ 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,                     │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                            │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key':        │
│ 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1',          │
│ 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                        │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\main.py", line 132, in <module>
    raise err
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\main.py", line 69, in run_many
    main()
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\video_creation\screenshot_downloader.py", line 103, in get_screenshots_of_reddit_posts
    page.locator('[name="username"]').fill(settings.config["reddit"]["creds"]["username"])
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\sync_api\_generated.py", line 16045, in fill
    self._sync(
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 212, in fill
    return await self._frame.fill(self._selector, strict=True, **params)
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\_impl\_frame.py", line 528, in fill
    await self._channel.send("fill", locals_to_params(locals()))
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "C:\Users\abhra\PycharmProjects\RedditVideoBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[name=\"username\"]")
============================================================

```

**Comment by spaidevelopers** [comment]
Same issue I am having

**Comment by louisnahser** [comment]
Same for me

**Comment by skylarhknight** [comment]
I'm having the same problem:((

**Comment by javi22020** [comment]
Same here

**Comment by MagnusCarlsen26** [comment]
same

**Comment by spaidevelopers** [comment]
I solved this error by doing modifications in screenshot_downloader.py, reddit new interface has different classes.

**Comment by CherryDT** [comment]
> I solved this error by doing modifications in screenshot_downloader.py, reddit new interface has different classes.

That's great, could you maybe share them with us?

**Comment by Cyteon** [comment]
Check out my fork https://github.com/Cyteon/RedditVideoMakerBot/, currently working on merging it

**Comment by Faycal-S** [comment]
It's solved here : https://github.com/elebumm/RedditVideoMakerBot/pull/1986

**Comment by CherryDT** [comment]
Well, it still exists as there hasn't been any new version since.
