### ISSUE TITLE
Randomly getting an error at generating an MP3 audio file

### ISSUE THREAD

**Issue by daud-ahn** [elebumm/RedditVideoMakerBot#542]
This error does not always happen, even on the same post, sometimes it will eventually work if you retry a few times, or you fiddle around with `COMMENT_LENGTH_RANGE` and `MAX_COMMENT_LENGTH`, or both, I'm not sure.

Update on the temporary 'fix': after running the script a few dozen times, I can confirm that you need to fiddle around with `COMMENT_LENGTH_RANGE` and `MAX_COMMENT_LENGTH` too  

When I checked the Reddit post itself, it does not contain excessively large/long posts despite the error saying that 'Text length is too long!'.

Terminal output attached [here](https://github.com/elebumm/RedditVideoMakerBot/files/8933331/dump.txt)
[pastebin](https://pastebin.com/2T2uz3WV)
[Reddit post in question](https://www.reddit.com/r/AskReddit/comments/vesnz1/what_helps_you_keep_on_keepin_on/)

**Comment by ddivide** [comment]
we have same problem 
what did you put COMMENT_LENGTH_RANGE and MAX_COMMENT_LENGTH? 500?

**Comment by daud-ahn** [comment]
> we have same problem 
> what did you put COMMENT_LENGTH_RANGE and MAX_COMMENT_LENGTH? 500?

I put either 100 or 50, I just inputting those numbers randomly until it works

**Comment by WorriedTripod68** [comment]
Where is the “MAX_COMMENT_LENGTH” stored? I’ve looked in the py file it said it was in but I couldn’t find it

**Comment by daud-ahn** [comment]
> Where is the “MAX_COMMENT_LENGTH” stored? I’ve looked in the py file it said it was in but I couldn’t find it

I'm not sure what you meant with 'it was in' but, `MAX_COMMENT_LENGTH` is stored in `.env` file

**Comment by JasonLovesDoggo** [comment]
fixed.

**Comment by daud-ahn** [comment]
> fixed.

still getting the same error even after updating local repo, I assume the fix is still in PR?

**Comment by JasonLovesDoggo** [comment]
Yeah It is in the 2.1 PR I'm waiting for that to get merged tho
