### ISSUE TITLE
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

### ISSUE THREAD

**Issue by Ohmnito** [elebumm/RedditVideoMakerBot#806]
After installing the new version and launching it I get the mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame error.
It only happens with some threads, probably something that has to do with one of the comments not being text...

**Comment by Ohmnito** [comment]
Actually, I just found a solution.
In subreddit/subreddit.py, at the top before 

def get_subreddit_threads(POST_ID: str):


add this:

```
TEXT_WHITELIST = set("abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890")


def textify(text):
    return "".join(filter(TEXT_WHITELIST.__contains__, text))
```


and replacing at the bottom

if len(top_level_comment.body) <= int(getenv("MAX_COMMENT_LENGTH", "500")):

by

```
if len(top_level_comment.body) <= int(getenv("MAX_COMMENT_LENGTH", "500")) and len(textify(top_level_comment.body)) >=2:
```

Everything works now

**Comment by MPagliari** [comment]
Is there a reason we are not allowing "% ? ! , ." as these will change the TTS voice when necessary?

**Comment by William9923** [comment]
hi, @JasonLovesDoggo sorry to ping you, but it seems that this problem happens a lot. Could you maybe include this fix for further release (or should this be handled with v2.2, im not sure)?

**Comment by IslaFTW** [comment]
This error is happening to everyone, I tried to do your fix @Ohmnito  but I didn't succeed, could you share your version with the fix already implemented?

**Comment by Ohmnito** [comment]
@IslaFTW here's the full code for the subreddit.py file

```
import re
from os import getenv

import praw
from praw.models import MoreComments

from utils.console import print_step, print_substep
from utils.subreddit import get_subreddit_undone
from utils.videos import check_done


TEXT_WHITELIST = set("abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890")


def textify(text):
    return "".join(filter(TEXT_WHITELIST.__contains__, text))



def get_subreddit_threads(POST_ID: str):
    """
    Returns a list of threads from the AskReddit subreddit.
    """

    print_substep("Logging into Reddit.")

    content = {}
    if str(getenv("REDDIT_2FA")).casefold() == "yes":
        print("\nEnter your two-factor authentication code from your authenticator app.\n")
        code = input("> ")
        print()
        pw = getenv("REDDIT_PASSWORD")
        passkey = f"{pw}:{code}"
    else:
        passkey = getenv("REDDIT_PASSWORD")
    username = getenv("REDDIT_USERNAME")
    if username.casefold().startswith("u/"):
        username = username[2:]
    reddit = praw.Reddit(
        client_id=getenv("REDDIT_CLIENT_ID"),
        client_secret=getenv("REDDIT_CLIENT_SECRET"),
        user_agent="Accessing Reddit threads",
        username=username,
        passkey=passkey,
        check_for_async=False,
    )

    # Ask user for subreddit input
    print_step("Getting subreddit threads...")
    if not getenv(
        "SUBREDDIT"
    ):  # note to user. you can have multiple subreddits via reddit.subreddit("redditdev+learnpython")
        try:
            subreddit = reddit.subreddit(
                re.sub(r"r\/", "", input("What subreddit would you like to pull from? "))
                # removes the r/ from the input
            )
        except ValueError:
            subreddit = reddit.subreddit("askreddit")
            print_substep("Subreddit not defined. Using AskReddit.")
    else:
        print_substep(f"Using subreddit: r/{getenv('SUBREDDIT')} from environment variable config")
        subreddit_choice = getenv("SUBREDDIT")
        if subreddit_choice.casefold().startswith("r/"):  # removes the r/ from the input
            subreddit_choice = subreddit_choice[2:]
        subreddit = reddit.subreddit(
            subreddit_choice
        )  # Allows you to specify in .env. Done for automation purposes.

    if POST_ID:  # would only be called if there are multiple queued posts
        submission = reddit.submission(id=POST_ID)
    elif getenv("POST_ID") and len(getenv("POST_ID").split("+")) == 1:
        submission = reddit.submission(id=getenv("POST_ID"))
    else:

        threads = subreddit.hot(limit=25)
        submission = get_subreddit_undone(threads, subreddit)
    submission = check_done(submission)  # double-checking
    if submission is None:
        return get_subreddit_threads(POST_ID)  # submission already done. rerun
    upvotes = submission.score
    ratio = submission.upvote_ratio * 100
    num_comments = submission.num_comments

    print_substep(f"Video will be: {submission.title} :thumbsup:", style="bold green")
    print_substep(f"Thread has {upvotes} upvotes", style="bold blue")
    print_substep(f"Thread has a upvote ratio of {ratio}%", style="bold blue")
    print_substep(f"Thread has {num_comments} comments", style="bold blue")

    content["thread_url"] = f"https://reddit.com{submission.permalink}"
    content["thread_title"] = submission.title
    content["thread_post"] = submission.selftext
    content["thread_id"] = submission.id
    content["comments"] = []

    for top_level_comment in submission.comments:
        if isinstance(top_level_comment, MoreComments):
            continue
        if top_level_comment.body in ["[removed]", "[deleted]"]:
            continue  # # see https://github.com/JasonLovesDoggo/RedditVideoMakerBot/issues/78
        if not top_level_comment.stickied:
            if len(top_level_comment.body) <= int(getenv("MAX_COMMENT_LENGTH", "500")) and len(textify(top_level_comment.body)) >=2:
                if (
                    top_level_comment.author is not None
                ):  # if errors occur with this change to if not.
                    content["comments"].append(
                        {
                            "comment_body": top_level_comment.body,
                            "comment_url": top_level_comment.permalink,
                            "comment_id": top_level_comment.id,
                        }
                    )
    print_substep("Received subreddit threads Successfully.", style="bold green")
    return content


```

**Comment by IslaFTW** [comment]
> @IslaFTW here's the full code for the subreddit.py file
> 
> ```
> import re
> from os import getenv
> 
> import praw
> from praw.models import MoreComments
> 
> from utils.console import print_step, print_substep
> from utils.subreddit import get_subreddit_undone
> from utils.videos import check_done
> 
> 
> TEXT_WHITELIST = set("abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ 1234567890")
> 
> 
> def textify(text):
>     return "".join(filter(TEXT_WHITELIST.__contains__, text))
> 
> 
> 
> def get_subreddit_threads(POST_ID: str):
>     """
>     Returns a list of threads from the AskReddit subreddit.
>     """
> 
>     print_substep("Logging into Reddit.")
> 
>     content = {}
>     if str(getenv("REDDIT_2FA")).casefold() == "yes":
>         print("\nEnter your two-factor authentication code from your authenticator app.\n")
>         code = input("> ")
>         print()
>         pw = getenv("REDDIT_PASSWORD")
>         passkey = f"{pw}:{code}"
>     else:
>         passkey = getenv("REDDIT_PASSWORD")
>     username = getenv("REDDIT_USERNAME")
>     if username.casefold().startswith("u/"):
>         username = username[2:]
>     reddit = praw.Reddit(
>         client_id=getenv("REDDIT_CLIENT_ID"),
>         client_secret=getenv("REDDIT_CLIENT_SECRET"),
>         user_agent="Accessing Reddit threads",
>         username=username,
>         passkey=passkey,
>         check_for_async=False,
>     )
> 
>     # Ask user for subreddit input
>     print_step("Getting subreddit threads...")
>     if not getenv(
>         "SUBREDDIT"
>     ):  # note to user. you can have multiple subreddits via reddit.subreddit("redditdev+learnpython")
>         try:
>             subreddit = reddit.subreddit(
>                 re.sub(r"r\/", "", input("What subreddit would you like to pull from? "))
>                 # removes the r/ from the input
>             )
>         except ValueError:
>             subreddit = reddit.subreddit("askreddit")
>             print_substep("Subreddit not defined. Using AskReddit.")
>     else:
>         print_substep(f"Using subreddit: r/{getenv('SUBREDDIT')} from environment variable config")
>         subreddit_choice = getenv("SUBREDDIT")
>         if subreddit_choice.casefold().startswith("r/"):  # removes the r/ from the input
>             subreddit_choice = subreddit_choice[2:]
>         subreddit = reddit.subreddit(
>             subreddit_choice
>         )  # Allows you to specify in .env. Done for automation purposes.
> 
>     if POST_ID:  # would only be called if there are multiple queued posts
>         submission = reddit.submission(id=POST_ID)
>     elif getenv("POST_ID") and len(getenv("POST_ID").split("+")) == 1:
>         submission = reddit.submission(id=getenv("POST_ID"))
>     else:
> 
>         threads = subreddit.hot(limit=25)
>         submission = get_subreddit_undone(threads, subreddit)
>     submission = check_done(submission)  # double-checking
>     if submission is None:
>         return get_subreddit_threads(POST_ID)  # submission already done. rerun
>     upvotes = submission.score
>     ratio = submission.upvote_ratio * 100
>     num_comments = submission.num_comments
> 
>     print_substep(f"Video will be: {submission.title} :thumbsup:", style="bold green")
>     print_substep(f"Thread has {upvotes} upvotes", style="bold blue")
>     print_substep(f"Thread has a upvote ratio of {ratio}%", style="bold blue")
>     print_substep(f"Thread has {num_comments} comments", style="bold blue")
> 
>     content["thread_url"] = f"https://reddit.com{submission.permalink}"
>     content["thread_title"] = submission.title
>     content["thread_post"] = submission.selftext
>     content["thread_id"] = submission.id
>     content["comments"] = []
> 
>     for top_level_comment in submission.comments:
>         if isinstance(top_level_comment, MoreComments):
>             continue
>         if top_level_comment.body in ["[removed]", "[deleted]"]:
>             continue  # # see https://github.com/JasonLovesDoggo/RedditVideoMakerBot/issues/78
>         if not top_level_comment.stickied:
>             if len(top_level_comment.body) <= int(getenv("MAX_COMMENT_LENGTH", "500")) and len(textify(top_level_comment.body)) >=2:
>                 if (
>                     top_level_comment.author is not None
>                 ):  # if errors occur with this change to if not.
>                     content["comments"].append(
>                         {
>                             "comment_body": top_level_comment.body,
>                             "comment_url": top_level_comment.permalink,
>                             "comment_id": top_level_comment.id,
>                         }
>                     )
>     print_substep("Received subreddit threads Successfully.", style="bold green")
>     return content
> ```

ty, but still having the error :(

![image](https://user-images.githubusercontent.com/60049112/177019044-00e5a5a5-a1a4-4282-b390-2b035e3408d7.png)

**Comment by JasonLovesDoggo** [comment]
Fixed in develop

**Comment by dasbts** [comment]
Still getting this in the newest develop branch version. Tried the proposed solution in this thread but it didn't work. How did I get the error in the newest version? I was getting another error which I tried to fix, that error was that './assets/temp/mp3/0-0.part.mp3' was already in use and thus gave a PermissionError (which looped infinitely and flooded the CMD/terminal), so I altered cleanup.py with the following at row 25: 
```
            try:
                os.remove("./assets/temp/mp3/" + file)
            except:
                pass
```

This gave the following "can't sync to MPEG frame" error: 
```
Traceback (most recent call last):
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 61, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 50, in run_many
    main()
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\main.py", line 38, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\TTS\engine_wrapper.py", line 67, in run
    self.split_post(comment["comment_body"], idx)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\TTS\engine_wrapper.py", line 82, in split_post
    self.call_tts(f"{idx}-{idy}.part", text_cut)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\TTS\engine_wrapper.py", line 94, in call_tts
    self.length += MP3(f"{self.path}/{filename}.mp3").info.length
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\venv\lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\venv\lib\site-packages\mutagen\_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\venv\lib\site-packages\mutagen\id3\_file.py", line 421, in load
    self.info = self._Info(fileobj, offset)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\venv\lib\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "E:\Python\VideoGenerator\newest\RedditVideoMakerBot\venv\lib\site-packages\mutagen\mp3\__init__.py", line 402, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
```

**Comment by washeido** [comment]
i'm having the exact same error. I was able to make videos before, but now it's bricked
